### PR TITLE
Added Hash and compare #26

### PR DESCRIPTION
**Pull request by FireFlyForLife**
Added std::hash specializations to all reflifc classes.
Added all compare operations to reflifc classes.

Please note that I branched off from the previous PR, (#28 ). Feel free to pull that one first, then I will resolve any merge conflicts if needed. All the work for this PR is in [e649da6](https://github.com/AndreyG/ifc-reader/pull/29/commits/e649da6dea584df4fa465f3ba3fa198b7729b914) and [ca5da83](https://github.com/AndreyG/ifc-reader/pull/29/commits/ca5da83a9b9695a2596bc4348801111be730bd22)

### CODE REVIEW

**Comment by AndreyG** [comment]
Please, pass all `reflifc` types by value to functions (`operator <=>`, `hash::operator()`), because these types are small and trivially copyable.

**Comment by FireFlyForLife** [comment]
That is pretty unconventional, by reference generally has negligible performance overhead. And in this specific `reflifc` case, none at all. 
Since the [msvc x64 calling convention is __fastcall](https://learn.microsoft.com/en-us/cpp/build/x64-calling-convention?view=msvc-170#parameter-passing), which will will put your struct by value on the stack anyway, with a pointer in the register. So the same as passing by reference.

But if you are really keen on this I could change it.

**Comment by FireFlyForLife** [comment]
I rebased so this PR only has the changes related to the issue. Let me know if you want me to go through the 57 files to change const& to by value everywhere.

**Comment by AndreyG** [comment]
> That is pretty unconventional, by reference generally has negligible performance overhead.

I don't agree, this is conventional: http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rf-in.

> And in this specific `reflifc` case, none at all.

`reflifc` types are similar to `std::string_view` or `std::span`. And these types should be passed by value: https://quuxplusone.github.io/blog/2021/11/09/pass-string-view-by-value.

**Comment by FireFlyForLife** [comment]
I meant unconventional to equality operators and std::hash specializations, eg: https://devblogs.microsoft.com/cppblog/simplify-your-code-with-rocket-science-c20s-spaceship-operator/ 

std::string_view has much different conversions and semantics. But I guess I will start going through all the files.

**Comment by FireFlyForLife** [comment]
While starting to convert them, I noticed that `operator<=>` actually requires the argument to be const T& for it to be defaulted. So I will only be doing the std::hash'es

**Comment by FireFlyForLife** [comment]
Moved over all std hash specialisations to pass by value.

**Comment by AndreyG** [comment]
> While starting to convert them, I noticed that operator<=> actually requires the argument to be const T& for it to be defaulted.

This restriction is only for member `operator<=>` just for symmetry, because implicit `this` parameter is passed by const reference. But it's possible to define defaulted `operator<=>` as free function acceptiong parameters by value: https://godbolt.org/z/46Pevj6Yc.

**Pull request merged**
