### PR TITLE
tune: Make .d.json as optional (when compiled as API interface)

### PR DESCRIPTION
**Pull request by tapika**
https://github.com/NTSFka/CMakeCxxModules.git

can be compiled resulting only in one .ifc file without .d.json - add support for loading that one.

### CODE REVIEW

**Comment by AndreyG** [comment]
Please, see [this comment](https://github.com/AndreyG/ifc-reader/pull/11#issuecomment-973043975). https://github.com/NTSFka/CMakeCxxModules.git generates old experimental Microsoft modules instead of using C++20 standard. I'm not sure that it makes sense to support it.

**Comment by tapika** [comment]
> Please, see [this comment](https://github.com/AndreyG/ifc-reader/pull/11#issuecomment-973043975). https://github.com/NTSFka/CMakeCxxModules.git generates old experimental Microsoft modules instead of using C++20 standard. I'm not sure that it makes sense to support it.

And this would be my next question. Basically where I would like to apply this code is to get information on C++ interface, so I can map it to correspondent Python call. Maybe shortly I can describe - there exists various ways to bridge C/C++ and python. Fastest one of them is cffi, which more or less maps C to Python. I would prefer to use C++ interface (not C), and this in a turn maps to that I want to generate some C++ code to have C++-C bridge to cffi. From api call perspective I want to know what are interface names, what are function call parameters, and so on. I would start from simple API / simple interface, maybe only one .ifc file. But not excluding that later on I need to wrap more modules / more API's. So taking use case like this, how we could organize API's to work so that I could have simple API access to C++ interface classes ?

**Comment by tapika** [comment]
Maybe see also `https://foss.heptapod.net/pypy/cffi/-/issues/516` - and this is the code I want to generate: https://bitbucket.org/wlav/quaff/src/master/test/simple.py from this source code:
https://bitbucket.org/wlav/quaff/src/master/test/Simple.h

or alternatively same code rewritten as a module.

**Comment by AndreyG** [comment]
> I would start from simple API / simple interface, maybe only one .ifc file.

Just for the experiment you can manually create file `YourModuleName.ifc.d.json` with the following content
```
{
    "Data": {
        "ImportedModules": [],
        "ImportedHeaderUnits": []
    }
}
```
> So taking use case like this, how we could organize API's to work so that I could have simple API access to C++ interface classes?

If I understand your problem correctly, then something like this should work for you:
```
vector<ScopeDescriptor> get_namespaces_recursively(File const &);
std::ranges::view auto  get_classes               (ScopeDeclaration const & _namespace);
std::ranges::view auto  get_member_functions      (ScopeDeclaration const & _class);
```
It should be quite easy to implement this functions.

**Comment by AndreyG** [comment]
I have prototyped [implementation](https://github.com/AndreyG/ifc-reader/blob/enumerate_functions/lib/core/include/ifc/accessors.h), please let me know, if it works for you.

**Comment by tapika** [comment]
> Just for the experiment you can manually create file `YourModuleName.ifc.d.json` with the following content

Thanks for working demo, I'll check it later on.

Meanwhile - why this file should be needed - to my best understanding I will have header file, and pass it via compiler, and as a result will get .ifc file. It's also possible that compiler also creates .d.json file as well, but it should be in responsibility of compiler ?

**Comment by AndreyG** [comment]
Yes, .d.json file should be created by the compiler.

**Comment by tapika** [comment]
I'll abort this pull request, lets try to maybe chat over mail. I've got more questions on API you created , also on how to test it.

**Comment by tapika** [comment]
Can you send me mail maybe - I don't know yours. You can find my mail via my profile.
If we could chat directly ?

**Pull request closed without merging**
